//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_client.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id_Client { get; set; }
        public string First_Name { get; set; }
        public string Name { get; set; }
        public string Patronomyc { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Id_log_client { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Log_client Log_client { get; set; }
        public virtual Status Status { get; set; }
    }
}
