//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_client.DBmodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlientEntities : DbContext
    {
        public KlientEntities()
            : base("name=KlientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Log_client> Log_client { get; set; }
        public virtual DbSet<Log_rielt> Log_rielt { get; set; }
        public virtual DbSet<Rielt> Rielt { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
