//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract_client.DBmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rielt
    {
        public int Id_Rielt { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int DealShare { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Id_log_rielt { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Log_rielt Log_rielt { get; set; }
        public virtual Status Status { get; set; }
    }
}
